-- 코드를 입력하세요
SELECT S.FLAVOR	
FROM (
    SELECT J.FLAVOR, SUM(J.TOTAL_ORDER)+F.TOTAL_ORDER AS T
    FROM FIRST_HALF AS F
        RIGHT JOIN JULY AS J ON F.SHIPMENT_ID = J.SHIPMENT_ID
    GROUP BY J.FLAVOR
    ORDER BY T DESC) S
LIMIT 3