-- 코드를 작성해주세요

SELECT DISTINCT E.EMP_NO
    , E.EMP_NAME
    , CASE 
        WHEN N.CER_SCORE >= 96 THEN 'S'
        WHEN N.CER_SCORE >= 90 THEN 'A'
        WHEN N.CER_SCORE >= 80 THEN 'B'
        ELSE 'C'
    END AS GRADE
    , CASE 
        WHEN N.CER_SCORE >= 96 THEN E.SAL * 0.2
        WHEN N.CER_SCORE >= 90 THEN E.SAL * 0.15
        WHEN N.CER_SCORE >= 80 THEN E.SAL * 0.1
        ELSE 0
    END AS BONUS
FROM HR_EMPLOYEES AS E
    INNER JOIN (SELECT DISTINCT EMP_NO, SUM(SCORE) OVER (PARTITION BY EMP_NO) / 2 AS CER_SCORE
                FROM HR_GRADE) AS N ON E.EMP_NO = N.EMP_NO
ORDER BY E.EMP_NO
;